image: openjdk:8-alpine

stages:
    - test

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - .gradle

test:
    stage: test
    coverage: '/Total.*?([0-9]{1,3})%/'
    before_script:
        - apk add --no-cache grep
    script:
        - ./gradlew codeCoverageReport
        # The actual output that will be parsed by the code coverage
        - grep -oP "Total.*?%" build/reports/jacoco/html/index.html
    only:
        - master
        - merge_requests
        - tags
